### ISSUE TITLE
Expects a 32 byte hash value or hex encoded string. Got  22354e91f3393e.....

### ISSUE THREAD

**Issue by coin77** [stellarguard/secret-memo#1] opened 2020-05-11 14:45 UTC
* **I'm submitting a ...**
[ X] bug report

* **Summary**
Error: Expects a 32 byte hash value or hex encoded string. Got 22354e91f3393e739f0a70ca75ac25d1a1964958425e6ecfcd71eae049ecd07bdb6bbfbd79eb8de9

With the following code:
```
const { SecretMemo } = require('@stellarguard/secret-memo');
const StellarSdk = require('stellar-sdk');
//StellarSdk.Network.useTestNetwork();
const server = new StellarSdk.Server('https://horizon-testnet.stellar.org');

const secretKey = 'its a secret to everybody'; // keep it secret, keep it safe
const secretMemo = new SecretMemo(secretKey);

const keypair = StellarSdk.Keypair.fromSecret(
  'SCN4KLPCOKV3BDNNS323ULSWVF4ASMTRCV5H5IGUBV52MNT64XCZFE6W'
);

async function submitSecretMemo(secret) {
  const fee = await server.fetchBaseFee();
  const sourceAccount = await server.loadAccount(keypair.publicKey());
  const transaction = new StellarSdk.TransactionBuilder(sourceAccount, {
            fee: fee,
            networkPassphrase: StellarSdk.Networks.TESTNET
        })
    .addMemo(secretMemo.toMemo(secret))
    .addOperation(
      StellarSdk.Operation.payment({
        amount: '1',
        asset: StellarSdk.Asset.native(),
        destination: keypair.publicKey()
      })
    )
    .build();

  transaction.sign(keypair);
  const result = await server.submitTransaction(transaction);
  console.log('Submit result: ', result);
  return result;
}

async function readSecretMemo(transactionId) {
  const result = await server
    .transactions()
    .transaction(transactionId)
    .call();

  const transaction = new StellarSdk.Transaction(result.envelope_xdr);
  console.log('Your Secret:', secretMemo.fromMemo(transaction.memo));
}

(async () => {	
  const secret = 'drink more ovaltine';
  const txResult = await submitSecretMemo(secret);
  await readSecretMemo(txResult.hash);
})();

```

**Comment by pselden** [comment] 2020-05-18 05:37
I published version 2.0.0 with a dependency on the latest Stellar SDK and that seems to have fixed it. You'll have to make a few minor changes to this script:

(Using StellarSdk.TransactionBuilder.fromXDR and setting fee to be a string)

```ts
const { SecretMemo } = require('@stellarguard/secret-memo');
const StellarSdk = require('stellar-sdk');
//StellarSdk.Network.useTestNetwork();
const server = new StellarSdk.Server('https://horizon-testnet.stellar.org');

const secretKey = 'its a secret to everybody'; // keep it secret, keep it safe
const secretMemo = new SecretMemo(secretKey);

const keypair = StellarSdk.Keypair.fromSecret(
  'SCN4KLPCOKV3BDNNS323ULSWVF4ASMTRCV5H5IGUBV52MNT64XCZFE6W'
);

async function submitSecretMemo(secret) {
  const fee = await server.fetchBaseFee();
  const sourceAccount = await server.loadAccount(keypair.publicKey());
  const transaction = new StellarSdk.TransactionBuilder(sourceAccount, {
            fee: String(fee),
            networkPassphrase: StellarSdk.Networks.TESTNET
        })
    .addMemo(secretMemo.toMemo(secret))
    .addOperation(
      StellarSdk.Operation.payment({
        amount: '1',
        asset: StellarSdk.Asset.native(),
        destination: keypair.publicKey()
      })
    )
    .build();

  transaction.sign(keypair);
  const result = await server.submitTransaction(transaction);
  console.log('Submit result: ', result);
  return result;
}

async function readSecretMemo(transactionId) {
  const result = await server
    .transactions()
    .transaction(transactionId)
    .call();

  const transaction = StellarSdk.TransactionBuilder.fromXDR(result.envelope_xdr, networkPassphrase: StellarSdk.Networks.TESTNET);
  console.log('Your Secret:', secretMemo.fromMemo(transaction.memo));
}

(async () => {	
  const secret = 'drink more ovaltine';
  const txResult = await submitSecretMemo(secret);
  await readSecretMemo(txResult.hash);
})();

```

**Comment by Daniel-Fernandez-951** [comment] 2020-05-21 05:12
Attempted to just output the secret memo by using SecretMemo.toMemo:
```
const secretKey = 'its a secret to everybody';
const secretMemo = new SecretMemo(secretKey);

const data = 'qwsedrftgyhujikoiugfedr'; // Max size @ 23 characters

const memoReady = secretMemo.toMemo(data);
console.log(memoReady)
```

### Error reads:

> Error: Expects a 32 byte hash value or hex encoded string. Got dd1a3bf243f0
> 97c7e7c1a81c6f5a4e724fe587608713d540a899d84cd3c4de1a046abd4d8280374b
> at Function._validateHashValue (.../node_modules/stellar-base/lib/memo.js:205:19)
> at new Memo (.../node_modules/stellar-base/lib/memo.js:86:14)
> at Function.hash (.../node_modules/stellar-base/lib/memo.js:272:14)
> at at SecretMemo.toMemo (node_modules/@stellarguard/secret-memo/build/main/lib/secret-memo.js:45:35)

Intending to just extract the encrypted and hashed string for use in URI building (`web+stellar:pay?destination=[]&memo_hash=[memoReady]`).

## Update:

By changing line 45 in `/node_modules/@stellarguard/secret-memo/build/main/lib/secret-memo.js` from `return stellar_sdk_1.Memo.hash(hash);` to `return stellar_sdk_1.hash(hash);`
 the output produced no errors.

**Comment by pselden** [comment] 2020-05-31 03:57
Can you let me know what version of stellar-sdk and stellar-base you're using? I cannot for the life of me reproduce this.

**Comment by Daniel-Fernandez-951** [comment] 2020-06-04 21:10
> Can you let me know what version of stellar-sdk and stellar-base you're using? I cannot for the life of me reproduce this.

Stellar-SDK Version   = 5.0.1
Stellar-BASE Version = 3.0.2

Thank you for your time.

**Comment by Jmunapo** [comment] 2020-11-23 08:58
Any fix for this? I'm getting a same error 
``` "stellar-sdk": "^7.0.0"```

**Comment by Jmunapo** [comment] 2020-11-23 13:38
```js
const {
    AES: { encrypt, decrypt },
    pad: { AnsiX923 },
    mode: { CTR },
    format,
    enc: { Utf8, Hex },
    PBKDF2
} = require("crypto-js");

const crypto = require('crypto');

const { Memo, MemoHash } = require("stellar-sdk");


const MAX_MEMO_LENGTH = 31;

const SALT = "e92798575ce70cf39cd984518d7e9de5"; //From ENV
const IV = "410f3193505e98a290fcaebde9cf4184"; //From ENV

exports.SecretMemo = class SecretMemo {

    constructor(secret) {
        this.secret = secret;
    }

    /**
     * Encrypts user's memo
     * @param {string} data User Data
     * @returns {MemoHash}
     */
    toMemo(data) {

        if (data.length > MAX_MEMO_LENGTH) {
            throw new Error(`The data string cannot be longer than ${MAX_MEMO_LENGTH} characters`);
        }

        const required_padding = 16 - data.length;

        if (data.length < 16) {
            const padding = crypto.randomBytes(required_padding)
                .toString('hex')
                .slice(0, required_padding);
            const padding_size = String.fromCharCode(required_padding);
            console.log({ padding_size, required_padding });
            data = `${data}${padding}${padding_size}`;
        }

        const key = PBKDF2(this.secret, Hex.parse(SALT), {
            keySize: 8,
            iterations: 100
        });
        const encrypted = encrypt(data, key, {
            iv: Hex.parse(IV),
            padding: AnsiX923,
            mode: CTR

        });

        const hash = encrypted.toString(format.Hex);

        if (hash.length !== 64) {
            throw new Error(`Error, computed hash must be 64 characters long. Got ${hash.length}`);
        }

        return Memo.hash(hash);

    }

    /**
     * Decrypts memo from hash or MemoHash
     * @param {MemoHash|String} memo Memo or 64 bit String
     * @returns {string}
     */
    fromMemo(memo) {
        if (typeof memo !== 'string') {
            console.log("Hash...");
            memo = memo.value instanceof Buffer ? memo.value.toString('hex') : memo.value;
        }
        const key = PBKDF2(this.secret, Hex.parse(SALT), {
            keySize: 8,
            iterations: 100
        });

        let decrypted = decrypt(memo, key, {
            iv: Hex.parse(IV),
            padding: AnsiX923,
            mode: CTR,
            format: format.Hex
        }).toString(Utf8);

        const last_char = decrypted.slice(-1);

        const code_point = Number(last_char.codePointAt(0));

        if (!isNaN(code_point) && 1 <= code_point && code_point <= 16) {
            decrypted = decrypted.slice(0, -(1 + last_char.charCodeAt(0)));
        }

        return decrypted;
    }
}

```

**Comment by pselden** [comment] 2020-11-23 13:49
@Jmunapo can you let me know exact versions of nodejs, stellar-sdk, stellar-base, and crypter you're using? If I change the implementation too much it will become incompatible with memos generated with previous versions of this lib so I need to be careful.

**Comment by pselden** [comment] 2020-11-23 13:50
And can you also download the code and run "npm test" or "yarn test" and see if those pass for you.

**Closed as completed** 2020-11-23 15:15 UTC

**Comment by pselden** [comment] 2020-11-23 15:18
I published 2.0.1 to fix this and will publish 3.0.0 shortly to include bump to stellar-sdk peer dependency.

**Comment by Jmunapo** [comment] 2020-11-23 15:44
It's the version of Cryptr which changed the encryption algorithm from aes-256-ctr to aes-265-gcm which cause the hash to be 80 on your MAX_MEMO

________________________________

**Comment by pselden** [comment] 2020-11-23 15:49
It was actually a patch fix of cryptr which introduced some padding changes (cryptr was pinned to 4.x but there was an unintended breaking change in 4.0.2). I inlined Cryptr with the old version since it's small and easy to maintain if needed.
